#!/bin/bash

set -e

range="$1"
filename="$2"

if [[ $# -ge 3 ]]; then
  from_commit="$3"
else
  from_commit="HEAD"
fi

out="from commit: $from_commit"$'\n\n'

blame_out="$(git blame -sL "$range" "$from_commit" -- "$filename" 2>&1)" || exit 0

cat <<< "$out$blame_out"
echo

last_commit="$(
  <<< "$blame_out" \
  sed 's/ .*//' \
  | sort \
  | uniq \
  | xargs -r git show -s --format='%cI %h' \
  | sort -k1 \
  | tail -1 \
  | cut -d' ' -f2
)"

"$0" "$range" "$filename" "$last_commit~"
